
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Chapter : Luban.BeanBase
{
    public Chapter(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["Description"].IsString) { throw new SerializationException(); }  Description = _buf["Description"]; }
        { if(!_buf["Image"].IsString) { throw new SerializationException(); }  Image = _buf["Image"]; }
        { if(!_buf["priceMultiplier"].IsNumber) { throw new SerializationException(); }  PriceMultiplier = _buf["priceMultiplier"]; }
        { if(!_buf["priceBase"].IsNumber) { throw new SerializationException(); }  PriceBase = _buf["priceBase"]; }
        { var __json0 = _buf["buildingList"]; if(!__json0.IsArray) { throw new SerializationException(); } BuildingList = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  BuildingList.Add(__v0); }   }
    }

    public static Chapter DeserializeChapter(JSONNode _buf)
    {
        return new Chapter(_buf);
    }

    public readonly int ID;
    public readonly string Name;
    public readonly string Description;
    /// <summary>
    /// icon in chapter select
    /// </summary>
    public readonly string Image;
    /// <summary>
    /// affect the building price
    /// </summary>
    public readonly long PriceMultiplier;
    /// <summary>
    /// reward money amount
    /// </summary>
    public readonly long PriceBase;
    public readonly System.Collections.Generic.List<int> BuildingList;
   
    public const int __ID__ = -1891298259;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Name:" + Name + ","
        + "Description:" + Description + ","
        + "Image:" + Image + ","
        + "priceMultiplier:" + PriceMultiplier + ","
        + "priceBase:" + PriceBase + ","
        + "buildingList:" + Luban.StringUtil.CollectionToString(BuildingList) + ","
        + "}";
    }
}

}
