
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class MapEvent : Luban.BeanBase
{
    public MapEvent(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
    }

    public static MapEvent DeserializeMapEvent(JSONNode _buf)
    {
        return new MapEvent(_buf);
    }

    public readonly int ID;
   
    public const int __ID__ = 219757246;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "}";
    }
}

}
