
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.MONO
{
public partial class TbBuilding
{
    private readonly System.Collections.Generic.List<Building> _dataList;

    private System.Collections.Generic.Dictionary<(int, int), Building> _dataMapUnion;

    public TbBuilding(JSONNode _buf)
    {
        _dataList = new System.Collections.Generic.List<Building>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Building _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Building.DeserializeBuilding(_ele);  }
            _dataList.Add(_v);
        }
        _dataMapUnion = new System.Collections.Generic.Dictionary<(int, int), Building>();
        foreach(var _v in _dataList)
        {
            _dataMapUnion.Add((_v.ID, _v.Level), _v);
        }
    }

    public System.Collections.Generic.List<Building> DataList => _dataList;

    public Building Get(int ID, int Level) => _dataMapUnion.TryGetValue((ID, Level), out Building __v) ? __v : null;
    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}

}

