
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.MONO
{
public partial class TbChapter
{
    private readonly System.Collections.Generic.Dictionary<int, Chapter> _dataMap;
    private readonly System.Collections.Generic.List<Chapter> _dataList;
    
    public TbChapter(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Chapter>();
        _dataList = new System.Collections.Generic.List<Chapter>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Chapter _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Chapter.DeserializeChapter(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Chapter> DataMap => _dataMap;
    public System.Collections.Generic.List<Chapter> DataList => _dataList;

    public Chapter GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Chapter Get(int key) => _dataMap[key];
    public Chapter this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

