
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class PawnData : Luban.BeanBase
{
    public PawnData(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["Description"].IsString) { throw new SerializationException(); }  Description = _buf["Description"]; }
        { if(!_buf["ClassID"].IsNumber) { throw new SerializationException(); }  ClassID = _buf["ClassID"]; }
        { if(!_buf["BaseAttr"].IsObject) { throw new SerializationException(); }  BaseAttr = SLG.BasicStats.DeserializeBasicStats(_buf["BaseAttr"]);  }
        { if(!_buf["Growth"].IsObject) { throw new SerializationException(); }  Growth = SLG.BasicStats.DeserializeBasicStats(_buf["Growth"]);  }
        { if(!_buf["Cap"].IsObject) { throw new SerializationException(); }  Cap = SLG.BasicStats.DeserializeBasicStats(_buf["Cap"]);  }
    }

    public static PawnData DeserializePawnData(JSONNode _buf)
    {
        return new PawnData(_buf);
    }

    public readonly int ID;
    public readonly string Name;
    public readonly string Description;
    public readonly int ClassID;
    public readonly SLG.BasicStats BaseAttr;
    public readonly SLG.BasicStats Growth;
    public readonly SLG.BasicStats Cap;
   
    public const int __ID__ = 1389996146;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        BaseAttr?.ResolveRef(tables);
        Growth?.ResolveRef(tables);
        Cap?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Name:" + Name + ","
        + "Description:" + Description + ","
        + "ClassID:" + ClassID + ","
        + "BaseAttr:" + BaseAttr + ","
        + "Growth:" + Growth + ","
        + "Cap:" + Cap + ","
        + "}";
    }
}

}
