
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class PawnData : Luban.BeanBase
{
    public PawnData(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["Description"].IsString) { throw new SerializationException(); }  Description = _buf["Description"]; }
        { if(!_buf["triggerDistance"].IsNumber) { throw new SerializationException(); }  TriggerDistance = _buf["triggerDistance"]; }
        { if(!_buf["BaseAttr"].IsObject) { throw new SerializationException(); }  BaseAttr = SLG.BasicStats.DeserializeBasicStats(_buf["BaseAttr"]);  }
        { if(!_buf["mapEvent"].IsNumber) { throw new SerializationException(); }  MapEvent = (SLG.PawnMapEvent)_buf["mapEvent"].AsInt; }
    }

    public static PawnData DeserializePawnData(JSONNode _buf)
    {
        return new PawnData(_buf);
    }

    public readonly int ID;
    public readonly string Name;
    public readonly string Description;
    /// <summary>
    /// 大地图碰撞半径
    /// </summary>
    public readonly float TriggerDistance;
    public readonly SLG.BasicStats BaseAttr;
    /// <summary>
    /// 地图上做什么
    /// </summary>
    public readonly SLG.PawnMapEvent MapEvent;
   
    public const int __ID__ = 1389996146;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        BaseAttr?.ResolveRef(tables);
        
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Name:" + Name + ","
        + "Description:" + Description + ","
        + "triggerDistance:" + TriggerDistance + ","
        + "BaseAttr:" + BaseAttr + ","
        + "mapEvent:" + MapEvent + ","
        + "}";
    }
}

}
