
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class SkillData : Luban.BeanBase
{
    public SkillData(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["SkillName"].IsString) { throw new SerializationException(); }  SkillName = _buf["SkillName"]; }
    }

    public static SkillData DeserializeSkillData(JSONNode _buf)
    {
        return new SkillData(_buf);
    }

    public readonly int ID;
    public readonly string SkillName;
   
    public const int __ID__ = -300302981;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "SkillName:" + SkillName + ","
        + "}";
    }
}

}
