
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public SLG.TbConst TbConst {get; }
    public SLG.TbLanguage TbLanguage {get; }
    public SLG.Character Character {get; }
    public SLG.Item Item {get; }
    public SLG.Class Class {get; }
    public SLG.TileEffect TileEffect {get; }
    public SLG.Skill Skill {get; }
    public MONO.TbChapter TbChapter {get; }
    public MONO.TbBuilding TbBuilding {get; }
    public MONO.TbMapConfig TbMapConfig {get; }
    public MONO.TbMapEvent TbMapEvent {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbConst = new SLG.TbConst(loader("slg_tbconst"));
        TbLanguage = new SLG.TbLanguage(loader("slg_tblanguage"));
        Character = new SLG.Character(loader("slg_character"));
        Item = new SLG.Item(loader("slg_item"));
        Class = new SLG.Class(loader("slg_class"));
        TileEffect = new SLG.TileEffect(loader("slg_tileeffect"));
        Skill = new SLG.Skill(loader("slg_skill"));
        TbChapter = new MONO.TbChapter(loader("mono_tbchapter"));
        TbBuilding = new MONO.TbBuilding(loader("mono_tbbuilding"));
        TbMapConfig = new MONO.TbMapConfig(loader("mono_tbmapconfig"));
        TbMapEvent = new MONO.TbMapEvent(loader("mono_tbmapevent"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbConst.ResolveRef(this);
        TbLanguage.ResolveRef(this);
        Character.ResolveRef(this);
        Item.ResolveRef(this);
        Class.ResolveRef(this);
        TileEffect.ResolveRef(this);
        Skill.ResolveRef(this);
        TbChapter.ResolveRef(this);
        TbBuilding.ResolveRef(this);
        TbMapConfig.ResolveRef(this);
        TbMapEvent.ResolveRef(this);
    }
}

}
