//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.SLG
{

public sealed partial class Class
{
    private readonly Dictionary<int, SLG.ClassData> _dataMap;
    private readonly List<SLG.ClassData> _dataList;
    
    public Class(JSONNode _json)
    {
        _dataMap = new Dictionary<int, SLG.ClassData>();
        _dataList = new List<SLG.ClassData>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = SLG.ClassData.DeserializeClassData(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
        PostInit();
    }

    public Dictionary<int, SLG.ClassData> DataMap => _dataMap;
    public List<SLG.ClassData> DataList => _dataList;

    public SLG.ClassData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public SLG.ClassData Get(int key) => _dataMap[key];
    public SLG.ClassData this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}