//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.SLG
{

public sealed partial class ConstData :  Bright.Config.BeanBase 
{
    public ConstData(JSONNode _json) 
    {
        { if(!_json["TestConstValue"].IsNumber) { throw new SerializationException(); }  TestConstValue = _json["TestConstValue"]; }
        PostInit();
    }

    public ConstData(long TestConstValue ) 
    {
        this.TestConstValue = TestConstValue;
        PostInit();
    }

    public static ConstData DeserializeConstData(JSONNode _json)
    {
        return new SLG.ConstData(_json);
    }

    /// <summary>
    /// test read this value 
    /// </summary>
    public long TestConstValue { get; private set; }

    public const int __ID__ = 739339437;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "TestConstValue:" + TestConstValue + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
