//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.SLG
{

public sealed partial class Item
{
    private readonly Dictionary<int, SLG.ItemData> _dataMap;
    private readonly List<SLG.ItemData> _dataList;
    
    public Item(JSONNode _json)
    {
        _dataMap = new Dictionary<int, SLG.ItemData>();
        _dataList = new List<SLG.ItemData>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = SLG.ItemData.DeserializeItemData(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
        PostInit();
    }

    public Dictionary<int, SLG.ItemData> DataMap => _dataMap;
    public List<SLG.ItemData> DataList => _dataList;

    public SLG.ItemData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public SLG.ItemData Get(int key) => _dataMap[key];
    public SLG.ItemData this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}