//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.SLG
{

public sealed partial class TbLanguage
{
    private readonly Dictionary<string, SLG.LanguageData> _dataMap;
    private readonly List<SLG.LanguageData> _dataList;
    
    public TbLanguage(JSONNode _json)
    {
        _dataMap = new Dictionary<string, SLG.LanguageData>();
        _dataList = new List<SLG.LanguageData>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = SLG.LanguageData.DeserializeLanguageData(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
        PostInit();
    }

    public Dictionary<string, SLG.LanguageData> DataMap => _dataMap;
    public List<SLG.LanguageData> DataList => _dataList;

    public SLG.LanguageData GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public SLG.LanguageData Get(string key) => _dataMap[key];
    public SLG.LanguageData this[string key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}