//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.MONO
{

public sealed partial class Chapter :  Bright.Config.BeanBase 
{
    public Chapter(JSONNode _json) 
    {
        { if(!_json["ID"].IsNumber) { throw new SerializationException(); }  ID = _json["ID"]; }
        { if(!_json["Name"].IsString) { throw new SerializationException(); }  Name = _json["Name"]; }
        { if(!_json["Description"].IsString) { throw new SerializationException(); }  Description = _json["Description"]; }
        { if(!_json["Image"].IsString) { throw new SerializationException(); }  Image = _json["Image"]; }
        { if(!_json["priceMultiplier"].IsNumber) { throw new SerializationException(); }  PriceMultiplier = _json["priceMultiplier"]; }
        { if(!_json["priceBase"].IsNumber) { throw new SerializationException(); }  PriceBase = _json["priceBase"]; }
        { var __json0 = _json["buildingList"]; if(!__json0.IsArray) { throw new SerializationException(); } BuildingList = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  BuildingList.Add(__v0); }   }
        PostInit();
    }

    public Chapter(int ID, string Name, string Description, string Image, long priceMultiplier, long priceBase, System.Collections.Generic.List<int> buildingList ) 
    {
        this.ID = ID;
        this.Name = Name;
        this.Description = Description;
        this.Image = Image;
        this.PriceMultiplier = priceMultiplier;
        this.PriceBase = priceBase;
        this.BuildingList = buildingList;
        PostInit();
    }

    public static Chapter DeserializeChapter(JSONNode _json)
    {
        return new MONO.Chapter(_json);
    }

    public int ID { get; private set; }
    public string Name { get; private set; }
    public string Description { get; private set; }
    /// <summary>
    /// icon in chapter select
    /// </summary>
    public string Image { get; private set; }
    /// <summary>
    /// affect the building price
    /// </summary>
    public long PriceMultiplier { get; private set; }
    /// <summary>
    /// add to building price
    /// </summary>
    public long PriceBase { get; private set; }
    public System.Collections.Generic.List<int> BuildingList { get; private set; }

    public const int __ID__ = -1405369310;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Name:" + Name + ","
        + "Description:" + Description + ","
        + "Image:" + Image + ","
        + "PriceMultiplier:" + PriceMultiplier + ","
        + "PriceBase:" + PriceBase + ","
        + "BuildingList:" + Bright.Common.StringUtil.CollectionToString(BuildingList) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
