//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.MONO
{

public sealed partial class TbBuilding
{
    private readonly List<MONO.Building> _dataList;
    
    private Dictionary<(int, int), MONO.Building> _dataMapUnion;

    public TbBuilding(JSONNode _json)
    {
        _dataList = new List<MONO.Building>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = MONO.Building.DeserializeBuilding(_row);
            _dataList.Add(_v);
        }
        _dataMapUnion = new Dictionary<(int, int), MONO.Building>();
        foreach(var _v in _dataList)
        {
            _dataMapUnion.Add((_v.ID, _v.Level), _v);
        }
        PostInit();
    }

    public List<MONO.Building> DataList => _dataList;

    public MONO.Building Get(int ID, int Level) => _dataMapUnion.TryGetValue((ID, Level), out MONO.Building __v) ? __v : null;

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }

    
    partial void PostInit();
    partial void PostResolve();
}

}